### PR TITLE
test(nextly): type the hook-order callback so check-types passes on main

### PR DESCRIPTION
**Pull request by mobeenabdullah**
## What

`main` fails `pnpm --filter nextly check-types` since #1754:

```
src/domains/collections/__tests__/collection-mutation.test.ts(345,9): error TS7006: Parameter 'call' implicitly has an 'any' type.
```

The hook registry mock is an untyped record, so `.mock.calls` is `any` and the `findIndex` callback's parameter had no type. It is now typed as what a recorded call is, `unknown[]`.

## Why it reached main

The pre-push hook runs the repo-wide `check-types` but reports a failure as a NOTE rather than refusing, because the repo-wide check can be red for another lane's work. CI would have blocked, but its queue cannot drain (#1778), so the note was the only signal. #1781 makes the hook refuse a type error in the packages a push affects.

## Changeset

None. Test-only.

### CODE REVIEW

**Comment by mobeenabdullah** [comment]
@codex review
