### PR TITLE
fix(nextly): make scheduling a release work from the admin at all

### PR DESCRIPTION
**Pull request by mobeenabdullah**
**Scheduling a release fails with a 500 for every request the admin sends.** Reported from the running playground; reproduced, fixed, and covered.

```
RangeError: Invalid time value
    at Date.toISOString
    at statesTheSameDay   (api/releases.ts)
    at requireInstant
    at scheduleRelease
POST /admin/api/releases/<id>/schedule 500
```

## Cause

`statesTheSameDay` refuses an impossible date — February 30th parses and normalises to March 2nd — by re-reading the calendar day in the offset the caller stated. It took that offset with `raw.slice(19)`.

The offset does not sit at a fixed index. Seconds and milliseconds are both optional in the shape `ISO_INSTANT` accepts, so it begins anywhere from 16 (`…T09:00Z`) to 23 (`…T09:00:00.000+02:00`).

And `Date.prototype.toISOString()` **always** writes milliseconds — which is exactly what `ScheduleReleaseDialog` sends. Three faults from the one line:

| input | `slice(19)` | result |
|---|---|---|
| `…T09:00:00.000Z` | `".000Z"` | `Number("Z")` → `NaN` → Invalid Date → `toISOString` throws → **500** |
| `…T00:30:00.000+02:00` | `".000+02:00"` | `Number("+0")` → `0` → offset read as UTC → a valid instant **refused** as "a date that does not exist" |
| anything with ms | — | the impossible-date check compared the **wrong day**, so it was not checking what it exists to check |

The first is the outage. The second and third are worse in kind because they do not throw: one rejects legitimate input for every author east of Greenwich scheduling shortly after midnight, and the other silently disables a validation.

The offset is now matched from the end of the string.

## Why nothing caught it

**The instant contract had no test coverage at all** — verified with a control (the error message exists in product code, and no test names it). The one route test that schedules used `"2026-09-01T09:00:00Z"`: a hand-written second-precision string **the product never produces**.

So the new tests are written from what the client actually sends. `ADMIN_SHAPE` is `new Date("2026-09-01T09:00:00Z").toISOString()`, asserted to equal `"2026-09-01T09:00:00.000Z"`, rather than a literal anyone can typo into the shape that happens to work.

Cases: the admin shape; an offset instant with milliseconds (asserting the **offset is honoured**, not merely accepted); no-seconds; plain second-precision as a control; and three refusals — impossible date with and without milliseconds, and a zone-less local string.

**Break-verified.** Restoring `raw.slice(19)` fails three of the seven and reproduces the original `RangeError` stack through the route.

## Provenance

Mine, from #1390. It has been live on `main` since, and the feature has been unusable from the admin for that whole period — every release in the playground was scheduled through a path that 500s.

## Gates

Full pre-push hook, no bypass: lint 22/22, build 19/19, check-types 22/22, tests 7/7 — nextly **845 files**, zero failures. `fallow audit --base origin/main`: `pass`, 3 changed files, all `*_introduced` zero.

@codex please review

### CODE REVIEW

**Comment by mobeenabdullah** [comment]
Second fix pushed on this branch — the other half of the same report, so it stays one PR.

## The "Add to release" button could be seen and not used

Reported as "hiding behind the sidebar… can't click it properly… hover issue too". Reproduced and measured in the running admin rather than guessed at.

At a 1280 viewport:

```
button        x 1099-1256   y  96-132
sticky panel  x  936-1256   y 100-2220   (w-[320px])
document.elementFromPoint(1178, 114) -> the PANEL, not the button
buttonIsHit: false
```

Two faults stacked. Horizontally, the button's bar was right-aligned to the **full** content measure (max-width 1152 → right edge 1256), while the content column ends where the panel starts at 936. Vertically, the form begins at y=100 — above the bar's own bottom at 132 — because two `display: contents` wrappers sit between the form and its grid cell, so the form is promoted into the page shell's grid rather than laid out in the cell reserved for it. The panel is `sticky`, so it paints over the static bar and takes the pointer.

**I did not fix this with a z-index**, and that was the tempting fix. Raising the bar would have left it painted over a panel it still physically overlapped, and the button would still have been in the wrong place. The actual fault is that a document-level action was not with the other document-level actions: Copy shareable link, Save Draft and Publish all sit together at y=112, ending at x=817, comfortably clear of the panel. Adding a document to a release is the same kind of act.

So both editors now pass it through a new `documentActions` prop, composed into the `toolbarSlot` the header already offers plugins. The page keeps the release concern; the form stays unaware of releases, which is exactly what that slot exists for.

**Verified in the browser, both editors:** button now at x 548-705, panel begins at 936, `elementFromPoint` at its centre returns the button, and the dialog opens and adds. The control still hides where it should — checked against `landing-page` (`status: true`, present) and `homepage` (`status: false`, absent), so the lifecycle gate is intact rather than the button having simply vanished.

## And the scheduling fix is confirmed end to end

Against the running app, posting the exact shape the dialog sends:

```
POST /admin/api/releases/<id>/schedule   { "at": "2026-09-01T04:27:30.411Z", ... }
-> 200 { "message": "Release scheduled." }
```

Milliseconds and all — the shape that was returning 500.

## Gates

Full pre-push hook, no bypass: lint 22/22, build 19/19, check-types 22/22, tests 10/10 — nextly **845 files**, admin **338 files**, zero failures. `fallow audit --base origin/main`: `pass`, 7 changed files, all `*_introduced` zero.

@codex please review

**Comment by mobeenabdullah** [comment]
Both P1s worked. The first was a regression this branch introduced and the second was my own repair being the same defect one step removed — thank you for both.

## Keep the release trigger from submitting the document

Confirmed at the source before fixing: `packages/ui/src/components/button.tsx` renders `asChild ? Slot : "button"` and sets **no `type`**, so inside a form the trigger inherited HTML's `submit` default. Moving the control into the action cluster is what put it inside `<form>`, so this was introduced here.

The failure mode is the nasty kind — the dialog still opened, so it looked correct while saving the document underneath.

Fixed with an explicit `type="button"` on the trigger, which states the property on the element rather than relying on where it is mounted. Tested both ways:

- behaviourally — rendered inside a `<form onSubmit>`, clicking opens the dialog and `onSubmit` is **not** called;
- structurally — the attribute is present.

Both, deliberately: a future wrapper that happened to swallow submits would make the behavioural case pass while leaving the control unsafe anywhere else it is used. Break-verified — removing `type="button"` fails both.

## Derive the offset from the validated instant

Right, and it is worth naming what my fix was: a **private parser of a format declared elsewhere**, with `?? "Z"` turning any disagreement into a silent UTC fallback. That is the fixed-index bug's own shape at one remove — two readings of one format, agreeing until the format changes and only one is updated.

`ISO_INSTANT` now captures the offset itself and `requireInstant` keeps the match rather than discarding it, handing the captured offset to `statesTheSameDay`. One parser again.

I also rewrote the comment inside that function: it still described a fixed-index read that no longer happens there, and stale prose about a defect is worse than none.

**One correction to the obvious implementation.** I used a NAMED capture group first. It compiles under `packages/nextly` and fails the repo-wide gate:

```
playground:check-types: packages/nextly/src/api/releases.ts(211,61):
  error TS1503: Named capturing groups are only available when targeting 'ES2018' or later.
```

The playground compiles this source under an older target, which a package-local `tsc` never sees. It is a numbered group now, with every inner group made non-capturing so the index cannot drift, and a comment saying why the named form is unavailable.

## Gates

Full pre-push hook, no bypass: lint 22/22, build 19/19, check-types **22/22**, tests 10/10 — nextly **845 files**, admin **338 files**, zero failures.

Worth recording since it cost two attempts: an earlier run of this identical tree failed six unrelated files, all `Test timed out in 10000ms`, zero assertions, at machine load 25/36/29. All six passed in isolation (149 tests), and the run above is green at load 7.6. Same tree, so the reds were the machine.

@codex please review
