### PR TITLE
feat(nextly): a plugin can publish a widget source, and a slow one cannot hold the batch

### PR DESCRIPTION
**Pull request by mobeenabdullah**
Phase 5.1. Researched first — `research:plugin-contributed-widget-sources`
surveys Grafana, Directus, Strapi, Payload, Sanity and WordPress — and the
headline finding is that we should **not invent a contract**: core's `system:`
sources already have exactly the right one, and 5.1 is mostly a matter of
letting a plugin through the same door.

## What a plugin writes

```ts
definePlugin({
  name: "@acme/stripe",
  contributes: {
    widgetSources: [{
      source: {
        id: "plugin:stripe/revenue",
        label: "Revenue",
        kind: "plugin",
        supports: ["count"],
        fields: [{ name: "total", type: "number" }],
      },
      resolve: async (query, caller) => ({ op: "count", total: await mine(caller) }),
    }],
  },
});
```

Both halves travel in one value, so "registered but unanswerable" — discoverable,
passing validation, failing only when a reader places the card — is not a state a
plugin can reach.

## The two kinds now share one resolver store

`system:` and `plugin:` are answered identically, so giving plugins a store of
their own would have been two answers to "what answers this id". The invariant
that actually matters is not which kind owns a resolver but **which kinds may
carry one at all** — never `collection:` or `single:`, whose rows the
access-controlled Direct API is supposed to answer. That rule is stated once, in
`resolved-sources.ts`, and both doors go through it. `system-sources.ts` keeps
its narrow system-only entry point.

## What the signature guarantees, and what it does not

A resolver gets `(query, caller)` and reaches only what its own closure
captured. Every name in that query was checked against the plugin's **own
declared field list** before execution, so there is no caller-controlled string
for it to fetch. That has to stay structural: Directus mitigated an
import-endpoint SSRF with an IP denylist (CVE-2022-23080) and the denylist was
then bypassed by DNS rebinding (CVE-2023-26492). No validated escape hatch, ever.

**It does not guarantee that a resolver consults `caller`.** It cannot — the host
hands the caller over and the plugin decides. WordPress has required a
`permission_callback` on every REST route since 5.5 and plugins still ship
`__return_true` for it (CVE-2026-4019, CVE-2026-4020); Payload's Local API
disables access control by default. A required field is not an enforced check.
This is the same trust boundary a plugin's `init()`, hooks and services already
cross — a Nextly plugin is an ordinary npm dependency — and the docblocks say so
rather than implying a guarantee the shape cannot make.

## Boot, and why the refusals are fatal

The fold copies the jobs pattern. A disabled plugin contributes nothing; a
reserved namespace, a duplicate id and a missing resolver each throw at boot
**naming the plugin**. Warnings would not do: which resolver owned an id would be
decided by plugin load order, and the loser would simply never answer with
nothing anywhere to say so. Core registers its own sources first, so a plugin
shadowing one fails on the plugin's registration rather than inside core's.
`resetWidgetRegistries` already clears the store every boot, so a stale source
cannot outlive its plugin.

## The bounded slot

`runPrepared` had no timeout and the batch aggregates with `Promise.all`, so it
was only ever as fast as its slowest query: one that never settled held every
other card behind it and the reader saw **nothing**, not seven cards and one
error. I verified that myself before acting on it rather than taking the research
at its word. Thirty seconds, following Grafana's `[dataproxy]` default —
generous on purpose, since the bound exists to stop a hang becoming an outage,
not to police a slow query.

The race abandons rather than cancels, because a promise cannot be cancelled. So
the abandoned promise gets a no-op handler (an unhandled rejection would crash
the process) and the timer is `unref`'d (otherwise a fast slot keeps the process
alive for the remaining thirty seconds, which in a test run is a suite that
never exits).

This is here rather than in its own PR because it is what makes a third-party
resolver safe to admit: today's only resolvers are core's own local reads.

## Evidence

Every guard was broken individually and killed exactly its own test(s):

- each of the five fold guards — reserved namespace (3 cases), plugin namespace,
  disabled-plugin skip, duplicate id, missing resolver;
- the `plugin` arm on `ExecutableSource` — 2 cases;
- the kind guard in `registerResolvedSource` — the `collection:` case;
- the boot wiring — 2 cases;
- the slot bound — the two hang cases, which fail by hanging, since the hang is
  the defect.

Controls that must pass either way are present: a system source answered from
the shared store, and a slot that answers inside the budget.

`check-types`, `lint`, the full `nextly` unit suite (941 files, 11959 tests),
seven widget integration files on sqlite and the `plugin-sdk` suite all pass;
fallow reports `pass` with 0 introduced dead code and 0 introduced duplication.

## Two things worth a reviewer's eye

**`resolveExecutableSource`'s final guard now narrows to `never`** — every
declared kind is executable. I kept it and widened through a `string`: the
narrowing is a statement about TypeScript callers, not about what a separately
compiled plugin can hand over.

**Deliberately not in v1**, per the research: no caller-supplied URL or path
under any allowlist; `requiredPermission` stays advisory; no multi-query batching
at the resolver boundary (that is 5.3); no VM sandbox; no per-instance resolver
config bypassing query validation; no cross-source joins.

## Summary by CodeRabbit

- **New Features**
  - Added support for plugins to provide custom dashboard widget data sources.
  - Added validation for source identifiers, query fields, supported operations, and resolver availability.
  - Plugin data sources now receive the requesting caller and plugin context for authorized reads.
  - Added support for preserving verified identity claims when evaluating access rules.

- **Bug Fixes**
  - Widget queries now isolate failures between slots, including timeouts and non-serializable results.
  - Slow slots are stopped after a bounded timeout while successful sibling results remain available.
  - Invalid or unavailable plugin sources now produce clear errors during setup or execution.

### CODE REVIEW

**Comment by mobeenabdullah** [comment]
@codex review

**Comment by mobeenabdullah** [comment]
@codex please review this PR

File: packages/nextly/src/domains/widgets/index.ts [hunk 1]
```diff
@@ -104,3 +104,24 @@ export {
...
+ * an author writing the resolver inline inside `definePlugin` gets `query` and
+ * `caller` typed from the contextual type, and needs none of these names. What
+ * inference cannot do is let them declare the resolver as a standalone
+ * function, or hand it to a helper, which is exactly how a plugin with more
+ * than one source ends up written.
+ *
+ * `ReadCaller` travels with the resolver for the same reason: it is the second
+ * of the two arguments, so without it the parameter has no name to annotate.
+ */
+export type { SourceResolver as WidgetSourceResolver } from "./resolved-sources";
```
[the remark this answers is not in the document]
Comment (mobeenabdullah) [reply packages/nextly/src/domains/widgets/index.ts:130]: Right, and this one is squarely my error: I changed the resolver contract to three arguments and left the export pointing at the two-argument alias, so the name published specifically to let an author declare a named resolver rejected the parameter that makes a resolver useful.

Fixed in `c4d437e37`. `PluginSourceResolver` is published from `nextly` and `@nextlyhq/plugin-sdk` beside `WidgetSourceResolver`, the docblock on both says which is which, and `STABILITY.md` lists it on the same `@experimental` ladder.

Both names are kept rather than repointing the old one: `WidgetSourceResolver` is genuinely core's own shape, used by `registerSystemSource`, and collapsing them would let a `system:` resolver be typed as taking a context it never receives.

Test: `packages/plugin-sdk/src/widget-source-exports.test-d.ts`, using `expectTypeOf` rather than `@ts-expect-error` -- a directive suppresses any error on the line beneath it, so it would keep passing once the rejection stopped happening. Break-verified: typing the named resolver with `WidgetSourceResolver` fails `check-types` with TS2344 naming `SourceResolver`, which is the expected diagnostic rather than merely a red.

File: packages/nextly/src/domains/widgets/execute.ts [hunk 2]
```diff
@@ -386,7 +386,12 @@ export async function executeWidgetQuery(
   // `ReleasesService.find` asks its own `authorize` before it reads -- so a
   // filter applied here would be a second implementation of a rule this module
   // cannot see, agreeing on the day it is written and drifting afterwards.
-  if (executable.kind === "system") {
+  if (executable.kind === "system" || executable.kind === "plugin") {
+    // One arm for both, because the contract is one. A plugin's resolver is
+    // handed exactly what core's is and is trusted exactly as far: it reaches
+    // what its own closure captured, and nothing a caller wrote can be a URL
+    // or a table name by the time it arrives -- every name in `query` was
+    // checked against the source's own declared fields first.
```
[the remark this answers is not in the document]
Comment (mobeenabdullah) [reply packages/nextly/src/domains/widgets/execute.ts]: You are right and the claim was mine to get right. I verified it rather than taking it on faith: `assertOperatorValueShape` refuses only a plain OBJECT operand, so `where: { total: { equals: "http://attacker.example" } }` validates cleanly and reaches the resolver verbatim. "No caller-controlled string reaches the resolver" was false, and it was written into a security-relevant docblock where a plugin author would rely on it.

Fixed in `c4d437e37` by correcting what the contract SAYS rather than pretending to close it at the host. The docblocks now separate the two halves explicitly: what is bounded (field names, operators, operand shapes, all against the source's own declaration) and what is not (operand values, which a caller who may place a widget chooses). The rule that follows is stated plainly -- a resolver must not use any value out of `query` as an outbound URL, a path, or a table or column name without validating it against a closed set of its own.

Corrected in all three places an author could read it: `resolved-sources.ts`, the dispatch comment in `execute.ts`, and the `contributes.widgetSources` docblock in `contributions.ts`, which is the one they actually meet.

Deliberately NOT a host-side filter over those values, and the Directus chain already cited on this PR is the reason: the IP denylist for CVE-2022-23080 was itself bypassed by DNS rebinding (CVE-2023-26492). A filter over a value the plugin then dereferences is one round of research from being no filter, so the host declines to imply one and says so instead.

**Comment by mobeenabdullah** [comment]
@codex review

File: .changeset/a-plugin-can-answer-a-widgets-question.md [hunk 3]
```diff
@@ -0,0 +1,55 @@
...
+"@nextlyhq/blocks-engine": patch
+"@nextlyhq/blocks-react": patch
+"@nextlyhq/builder": patch
+"create-nextly-app": patch
+"@nextlyhq/eslint-config": patch
+"@nextlyhq/eslint-plugin": patch
+"@nextlyhq/module-specifiers": patch
+"nextly": patch
+"@nextlyhq/plugin-form-builder": patch
+"@nextlyhq/plugin-page-builder": patch
```
[the remark this answers is not in the document]
Comment (mobeenabdullah) [reply .changeset/a-plugin-can-answer-a-widgets-question.md:18]: Already done, in `c4d437e37`, which this review predates -- it read `d534fd017`. `@nextlyhq/plugin-mcp` is in the changeset's list, and `check-changesets.mjs` accepts it.

Worth recording what was behind it, because it is bigger than this file: `plugin-mcp` merging grew the lockstep group from 25 to 26, and 1,180 of the 1,181 changesets then on `main` were missing it. Any commit that stages one of them fails the gate, which is how I met it. I added it to the four my own merge staged; the rest are only checked when something touches them.

File: packages/nextly/src/domains/widgets/execute.ts [hunk 4]
```diff
@@ -386,7 +386,12 @@ export async function executeWidgetQuery(
...
     return executable.resolve(query, caller);
```
[the remark this answers is not in the document]
Comment (mobeenabdullah) [reply packages/nextly/src/domains/widgets/execute.ts:399]: This is the sharpest finding on the PR and you are right about the mechanism: `respondData` serializes the whole results array after `Promise.all` and outside every slot's catch, so a value the encoder refuses never fails its own slot -- it fails the response, and every sibling's rows go with it. That is precisely the outcome the per-slot shape exists to prevent, and `Record<string, unknown>` admits all three of the cases you name.

Fixed in `6efcd9c0e`. The result is round-tripped through `JSON` inside `runPrepared`'s boundary, so a refusal becomes that slot's error with the source named in the log. The cost is one serialization of a payload about to be serialized anyway.

Three tests, and the first was wrong on its first attempt in a way worth naming: I used a second, UNREGISTERED source for the bad slot, so it failed as "unavailable source" before the executor ran and passed with the guard removed. Both slots now name the same registered source and dispatch on the op. Break-verified after the repair: removing the guard fails `fails that slot alone, and the rest of the batch still answers` and `says so in the log, naming the source`, while `passes an ordinary result through unchanged` stays green.

File: .changeset/a-plugin-can-answer-a-widgets-question.md [hunk 5]
```diff
@@ -0,0 +1,61 @@
...
+"@nextlyhq/tsconfig": patch
+"@nextlyhq/ui": patch
+---
+
+A plugin can contribute a dashboard-widget DATA SOURCE. `contributes.widgetSources`
+takes a source and the server-side function that answers it, together: the
+source declares its queryable fields and supported ops the way every other
+source does, and the resolver is handed `(query, caller)` and nothing else.
+Because the query was validated against that declared field list first, no
+string the caller wrote reaches the resolver as a URL, a path or a table name.
```
[the remark this answers is not in the document]
Comment (mobeenabdullah) [reply .changeset/a-plugin-can-answer-a-widgets-question.md]: Correct, and it is the exact failure mode this PR's other thread is about: I corrected the implementation comments and left the release note asserting the contract they no longer describe. A changeset is the text an author reads first, so a stale guarantee there is worse than one in a docblock.

Fixed in `6efcd9c0e`. The note now says the resolver is handed the query, the caller and its plugin context, and separates what validation bounds (field names, operators, operand shapes, against the source's own declaration) from what it does not (operand values), with the rule that follows: treat every value in a query as caller-controlled, and never use one as a URL, a path, or a table or column name without checking it against a closed set.

File: packages/nextly/src/plugins/widgets/collect-widget-sources.ts [hunk 6]
```diff
@@ -0,0 +1,189 @@
...
+ * What it is NOT handed is a request, headers, or anything fetch-capable of its
+ * own. The context is the same one the plugin's `init` receives, bounded by
+ * `createPluginContext` — see `domains/widgets/resolved-sources` for why that
+ * boundary is structural.
+ */
+export type PluginSourceResolver = (
+  query: Parameters<SourceResolver>[0],
+  caller: Parameters<SourceResolver>[1],
+  ctx: PluginContext
+) => ReturnType<SourceResolver>;
```
[the remark this answers is not in the document]
Comment (mobeenabdullah) [reply packages/nextly/src/plugins/widgets/collect-widget-sources.ts:56]: Right, and the part that matters most is your reading of my test: the cast through `unknown` compiled, so it hid the fact that no plugin could write the call the contract tells them to write. A test that masks the defect it is supposed to demonstrate is worse than no test, and that one did.

Confirmed by reading both types: `UserContext` carries `id: string` and `email?: string`; `AuthUser` carries a branded `AuthUserId` and a required `email`. They genuinely do not meet.

Fixed in `6efcd9c0e` by publishing `callerReadOptions(caller)` -- it returns the `ServiceOpts` a managed read takes, and it is exported from `nextly` and `@nextlyhq/plugin-sdk` and listed in `STABILITY.md`. One assertion in the host replaces one in every plugin, and the host is the place that can justify it: the `ReadCaller` was built from a request it authenticated, so the id IS an authenticated user's. A plugin has no standing to make that claim about a value it was handed.

It also carries the half an author would most easily leave out. `authenticatedScope` is what keeps an API key judged on the scope stamped into it rather than the roles of whoever minted it; assembling the options by hand makes omitting it a one-word mistake with a security consequence, and building them in one place makes it impossible.

The integration test now calls it, and the remaining local shape is only over the `count` SIGNATURE -- the managed facade is generic over the install's own collections, which a fixture slug is not a member of. The identity no longer passes through a cast.

File: packages/nextly/src/di/register.ts [hunk 7]
```diff
@@ -2934,6 +2941,28 @@ async function initializePlugins(
...
+    // plugin's entities while believing they were its own.
+    //
+    // Validated across ALL plugins before the loop (`contributedSources`), so a
+    // duplicate id or a reserved namespace is refused naming both owners rather
+    // than discovered halfway through registration.
+    for (const contributed of contributedSources) {
+      if (contributed.owner !== plugin.name) continue;
+      registerResolvedSource(
+        { ...contributed.source, kind: "plugin" },
+        (query, caller) => contributed.resolve(query, caller, pluginContext)
```
[the remark this answers is not in the document]
Comment (mobeenabdullah) [reply packages/nextly/src/di/register.ts]: Agreed, and "overwrite" is the right word for what it was doing: the spread erased a declared kind before `registerSource` could run the check that would have caught it, so a malformed contribution booted successfully under semantics its author never wrote. Silently correcting a declaration is worse than refusing it.

Fixed in `6efcd9c0e`, taking both halves of your remedy. `PluginWidgetSource.source` is narrowed to `WidgetSource & { kind: "plugin" }`, so a TypeScript author declaring anything else is a compile error at the plugin. The fold keeps a runtime guard beside it for a plugin compiled separately, for JavaScript and for a cast, and it REFUSES rather than corrects, naming the plugin and the kind it declared. The boot then registers the source exactly as declared.

Test: `refuses a source declaring any kind but plugin`. Break-verified: disabling the guard fails it alone.

**Comment by mobeenabdullah** [comment]
@codex review

File: packages/nextly/src/domains/widgets/caller-read-options.ts [hunk 8]
```diff
@@ -0,0 +1,58 @@
...
+ */
+export function callerReadOptions(caller: ReadCaller): ServiceOpts {
+  return {
+    as: "user",
+    // The one assertion, and the reason it is sound is above: this identity
+    // came from a request the host authenticated. `email` is absent from a
+    // `UserContext` and unused by the access decision, which reads the id and
+    // the roles -- so widening it here would add a field no caller supplies
+    // and nothing consults.
+    user: caller.user as unknown as AuthUser,
```
[the remark this answers is not in the document]
Comment (mobeenabdullah) [reply packages/nextly/src/domains/widgets/caller-read-options.ts:53]: Confirmed by reading both ends, and you are right including about which direction is dangerous. `readCaller` calls `buildUserContext({ claims: auth.claims, ... })` and that spreads the claims as top-level properties; `resolveServiceOpts` then rebuilt the identity from id, name, email and roles alone, so every claim was dropped between the endpoint and the rule.

Fixed in `0db588718`, and in `resolveServiceOpts` rather than in `callerReadOptions` -- the rebuild is where they were lost, so fixing it at the widget helper would have left every other plugin read wrong in the same way.

The extra properties are carried as "whatever else the supplied identity had", so a caller passing a plain `AuthUser` contributes nothing and nothing existing changes; the declared fields still come from the identity rather than from the spread.

Tests in `service-opts.test.ts`: one asserting a tenant and a plan survive to the identity the rule is judged on, and a must-differ half asserting an identity carrying only the declared fields gains nothing -- without which a version attaching some fixed object to every caller would satisfy the first. Break-verified: dropping the claims again fails the first alone.

On the direction you named: `user.plan !== "suspended"` was the case I checked first, because it is the one that fails open. With the claim absent that expression is `undefined !== "suspended"`, which is true, and a suspended caller is admitted.

**Comment by mobeenabdullah** [comment]
@codex review

File: packages/nextly/src/domains/widgets/resolved-sources.ts [hunk 9]
```diff
@@ -0,0 +1,169 @@
...
+ * was itself bypassed by DNS rebinding (CVE-2023-26492). A host-side filter
+ * over a value the plugin then uses as a destination is one round of research
+ * from being no filter at all, so the host declines to imply one.
+ *
+ * ## What this contract does NOT promise
+ *
+ * That a resolver consults `caller`. It cannot: the host hands over the caller
+ * and the resolver decides what to do with it. Pairing the source and the
+ * resolver in one call makes "registered but unanswerable" unrepresentable, and
+ * the signature forecloses SSRF — neither proves a third party authorized
```
[the remark this answers is not in the document]
Comment (mobeenabdullah) [reply packages/nextly/src/domains/widgets/resolved-sources.ts:56]: Right on both counts. The claim also contradicted the "NOT BOUNDED" section thirty lines above it in the same docblock, which says operand values are caller-controlled — I corrected that section earlier and missed this sentence and the test comment.

Fixed in 8f51451cc (#1832). The docblock now says pairing the source and the resolver makes "registered but unanswerable" unrepresentable and validating the query keeps a malformed question out, and names the SSRF bound as the one the section above declines to claim. The test comment now says the declared field list bounds the SHAPE of the question and nothing more, and that operand values stay caller-controlled.

File: packages/nextly/src/domains/widgets/resolved-sources.ts [hunk 10]
```diff
@@ -0,0 +1,169 @@
...
+    // surface verbatim and says what to change.
+    throw NextlyError.invalidInput({
+      message:
+        `Invalid widget source: ${String(source?.id)}: a resolver may only be ` +
+        `registered for a "system:" or "plugin:" source, not kind ` +
+        `"${String(source?.kind)}"`,
+    });
+  }
+  registerSource(source);
+  resolvers().set(source.id, resolve);
```
[the remark this answers is not in the document]
Comment (mobeenabdullah) [reply packages/nextly/src/domains/widgets/resolved-sources.ts:153]: Correct, and it gives away exactly the guarantee the single signature exists to make.

Fixed in 8f51451cc (#1832). `registerSource` now returns the detached snapshot it stored, and `registerResolvedSource` keys the resolver from that — one read, taken where the copy is made. The return type widens from `void`, which is backward compatible for every caller.

Break-verified by name: restoring the second read of `source.id` fails the new case alone. The test reads the published id back from the source store rather than naming an expected value, since which read wins is the registry's business and pinning it would make the test a copy of the implementation.

One related thing I did NOT ship: `preparedSource` also reads `source.id` a second time, for the `isTaken` duplicate check, before `snapshot` reads it again — the same class one frame down, and a drifting id could get a source past the duplicate refusal. I wrote the fix, but every test I could construct to distinguish it depends on how many times `validateWidgetSource` reads `id`, which is an internal detail. Rather than ship an untested behaviour change I reverted it. Worth a separate issue if you want it closed.

File: packages/nextly/src/api/widget-query.ts [hunk 11]
```diff
@@ -350,6 +350,104 @@ async function warmReadDecisions(
...
+    // Attached to `work` itself, not to the race's result: the race settles on
+    // whichever arm wins, so on a timeout nothing would ever observe `work`.
+    void work.catch(() => undefined);
+
+    const deadline = new Promise<typeof timedOut>(resolve => {
+      timer = setTimeout(() => resolve(timedOut), SLOT_TIMEOUT_MS);
+      timer.unref?.();
+    });
+
+    const outcome = await Promise.race([work, deadline]);
```
[the remark this answers is not in the document]
Comment (mobeenabdullah) [reply packages/nextly/src/api/widget-query.ts:403]: Confirmed against `main`, and left OPEN deliberately — this one is not mechanical and I am not going to half-build it.

The race genuinely abandons rather than cancels; the docblock on `withinSlotBudget` already says so, which makes it a known gap rather than an oversight, and the per-request cap of 30 does nothing to bound what is already running.

Two things make it a design decision rather than an edit:

1. **The signal has nowhere obvious to go.** `PluginSourceResolver` derives its parameters from `SourceResolver` via `Parameters<>`, and `ctx` is already the third argument. An `AbortSignal` cannot simply become the third parameter without colliding, so the choice is between growing the positional list (`query, caller, ctx, signal`), moving to an options object, or hanging the signal off `ctx` for plugins and a third argument for core — which is asymmetric. All three change a contract published through `nextly` and `@nextlyhq/plugin-sdk` two days ago.

2. **The cap needs a product answer.** A process-wide in-flight limit has to say what happens when it is reached — queue the slot against its own 30s budget, or fail it immediately — and that is what a reader sees on a loaded dashboard, not an internal detail.

Raising both with the maintainer with options rather than picking for them. The four other threads on this PR and #1830 are fixed in #1832.

[the remark this answers is not in the document]
Comment (mobeenabdullah) [reply packages/nextly/src/api/widget-query.ts:403]: Half shipped, half deliberately deferred — recording which is which.

**Shipped** in 8663937ea (#1832): a resolver is now handed an `AbortSignal`, aborted the moment its slot budget expires, so abandoned work is told rather than merely dropped. It arrives in a `ResolverOptions` object rather than as a positional argument — `PluginSourceResolver` derives its parameters from core's `SourceResolver` and `ctx` already holds the third position, so a positional signal would have meant one thing to a plugin and another to core, and the next concern would collide again. Optional throughout, so every resolver written against the shipped contract compiles and behaves unchanged; a type test asserts that directly. `ResolverOptions` is published through `nextly` and `@nextlyhq/plugin-sdk`.

Break-verified at every link, since the signal is worth nothing unless it survives all of them: removing the abort fails the expiry case alone; aborting unconditionally fails the answered-in-time case alone; dropping the forward in the executor fails both hand-off cases; dropping it from the boot binding in `di/register` fails the plugin integration case alone — the link where every unit below it keeps passing while cancellation reaches no plugin at all.

**Deferred**: the process-wide in-flight cap, with the maintainer's agreement. It is additive and internal, so nothing is foreclosed by waiting, and it needs a measured saturation policy rather than a guessed one — the rule this programme already applies to query batching. It also needs a product answer this finding cannot supply: what a reader sees when the cap is reached, queued or refused.

Tracked as `task:widget-resolver-inflight-cap` in the programme ledger rather than left as an open thread on a merged PR. Resolving on that basis.
