### PR TITLE
test(admin): a drop target is an Over, not an Active, so check-types passes on main

### PR DESCRIPTION
**Pull request by mobeenabdullah**
## What

`main` fails `@nextlyhq/admin` `check-types` since #1776:

```
src/lib/builder/builder-rows.test.ts(137,52): error TS2741: Property 'disabled' is missing in type 'Active' but required in type 'Over'.
src/lib/builder/builder-rows.test.ts(141,52): (same)
```

Two `onDragEnd` cases built the drop target with the test's `Active` helper. dnd-kit's `Over` is a different shape: a resolved rect and a `disabled` flag. An `over` helper now builds one, the same shape `sortable-announcements.test.tsx` already uses.

## Why it reached main

Same as #1780: merged while CI's queue could not report (#1778), and the pre-push hook of the day printed the type error as a note. #1781 has since made the hook refuse a type error in the packages a push affects.

## Changeset

None. Test-only.

### CODE REVIEW

**Comment by mobeenabdullah** [comment]
@codex review
