### PR TITLE
refactor(nextly): move the internal field group modules and services

### PR DESCRIPTION
**Pull request by mobeenabdullah**
Continues the Components → Field Groups rename (task 011). A0.1 through A5 are merged; this is A6, the internal module and service layer. **Nothing here is a stored contract** — no table names, config keys, wire keys, routes or public types change.

## What changed

**Four directories moved** (`git mv`): `src/components/` → `src/field-groups/`, `src/domains/components/` → `domains/field-groups/`, `src/services/components/` → `services/field-groups/`, `src/schemas/dynamic-components/` → `schemas/dynamic-field-groups/`, along with their inner module filenames.

**Service classes and DI keys**: `ComponentRegistryService` → `FieldGroupRegistryService` and the same for Schema/Query/Mutation/Data, plus the matching container keys.

**Drizzle table symbols**: `dynamicComponents{,Pg,Mysql,Sqlite}` and `DynamicComponent{Record,Insert}`. The **table name string is untouched** — it lives in `STORAGE_FORMAT.registryTable` and flips in B2.

**Dead code removed**: `FieldGroupSchemaService.generateSchemaCode` had no callers, and neither did the five private helpers only it used (`mapFieldToDrizzleCode`, the three per-dialect code mappers, `getDialectConfig`, `collectRequiredImports`, `generateBaseColumnsCode`, `generateTimestampColumnsCode`). Verified `getDialectConfig` / `collectRequiredImports` elsewhere are `user-ext-schema-service`'s own private copies, and that `generateRuntimeSchema` — which *is* used — shares none of them. 346 lines deleted.

## What deliberately did NOT change

Four stored contracts spelled `components` survive verbatim, and I checked each after the sweep:

- `ManifestKind = "collections" | "singles" | "components"` (ui-schema manifest → **B2**)
- `Object.defineProperty(target, "components", …)` — the pre-rename namespace guard from A3b, which must keep answering to the old name
- `schema-hash.ts` `"components"` key
- `FieldAdminOptions["components"]` (React view overrides, which never rename)

## A note on how this was verified, because the rename was hazardous

Two earlier attempts were reset and redone rather than patched:

1. A `(\.\./)+components/config` rule looked like a no-op but **collapsed relative paths** — `$1` captures only the last repetition, so `../../components/config` became `../components/config`.
2. A barrel-import rule matched **any** bare `"components"` string, including the A3b legacy guard and the manifest kind — stored contracts.

The final sweep confines path rewriting to module-specifier lines and applies identifier rewrites separately. All 22 resulting type errors are gone; notably the ten `ExtractTablesWithRelations` errors were cascading from unresolvable schema imports, not a separate problem.

**The test-name diff needed normalizing.** Renaming `describe` blocks and files changes test *names*, so a raw name-level comparison reports pre-existing failures as new. After normalizing the renamed prefixes, branch-only failures are **zero** (baseline 400). One apparent regression, `deleteComponentDataInTransaction`, fails identically on `main` — verified by finding it in the baseline.

The export-contract test caught a real self-inflicted bug: the sweep renamed entries **inside its list of legacy names that must not be exported**, so it began asserting the new names were absent. Restored to the old spellings, which is the whole point of that list.

## Verification

`pnpm check-types` 19/19 · `pnpm lint` clean · `pnpm build` clean · zero branch-only test failures.

## ⚠️ Size

**99 files — deliberately just under the 100-file threshold** at which CodeRabbit and Greptile silently skip review and report a passing status. If a review round needs more files, it should go in a follow-up rather than tipping this over.

## Not in this PR

Task 079 is filed as the committed manifest stripping plugin field options — a schema-fidelity P2 unrelated to this rename, so it stays open on its own. `applyPluginSchemaContributions` (the non-deferred variant) does still lack production callers; the `Deferred` one is wired at `di/register.ts:405` and `cli/utils/config-loader.ts`. Both are separate calls from a directory move.

## Summary by CodeRabbit

* **Refactor**
  * Consolidated component functionality under the Field Groups architecture.
  * Updated schema, registry, data access, synchronization, and API workflows to use Field Groups consistently.
  * Preserved existing component behavior, validation, authorization, and request handling.

* **Documentation**
  * Updated configuration and module references to reflect the Field Groups terminology and structure.

* **Tests**
  * Updated unit and integration coverage to validate the renamed Field Groups services and workflows.

### CODE REVIEW

**Comment by mobeenabdullah** [comment]
@codex please review this PR

**Comment by mobeenabdullah** [comment]
@coderabbitai review

**Comment by mobeenabdullah** [comment]
@greptileai review

**Comment by mobeenabdullah** [comment]
@codex please review this PR

**Comment by mobeenabdullah** [comment]
@coderabbitai review

**Comment by mobeenabdullah** [comment]
@greptileai review

File: packages/nextly/src/domains/field-groups/services/field-group-registry-service.ts [hunk 1]
```diff
@@ -1,19 +1,19 @@
...
 
-import type { FieldGroupAdminOptions } from "../../../components/config/types";
-import { MAX_FIELD_GROUP_NESTING_DEPTH } from "../../../components/config/validate-field-group";
 import { toDbError } from "../../../database/errors";
+import { NextlyError } from "../../../errors";
+import type { FieldGroupAdminOptions } from "../../../field-groups/config/types";
+import { MAX_FIELD_GROUP_NESTING_DEPTH } from "../../../field-groups/config/validate-field-group";
 // PR 4 migration: switched the throw layer to NextlyError. Public messages now
 // follow §13.8 (no slug echoing); identifiers (slug, source, refs) move into
 // `logContext` so operators retain full diagnostic context.
```
[the remark this answers is not in the document]
Comment (mobeenabdullah) [reply packages/nextly/src/domains/field-groups/services/field-group-registry-service.ts]: Confirmed and fixed in `98ab25ba`. The comment referenced "PR 4 migration" and "§13.8", both of which the project rule forbids: comments describe the code, never tasks, plans or spec sections. Rewritten to state the runtime rationale directly.

Swept the category rather than the cited line, which found **nine more** in the moved directories: five further `§13.8` references in this same file (lines 177, 246, 303, 369, 405), the `PR 4 migration` block in `field-group-mutation-service.ts`, the same in `field-group-registry-service.test.ts`, and a "Builder redesign PR 2/3" reference in `field-groups/config/validate-field-group.ts`. All rewritten to describe behaviour. A grep for `PR [0-9]`, `§13.8` and `per the audit` across the four moved directories now returns nothing.

File: packages/nextly/src/domains/field-groups/services/teardown-entity-field-group-data.ts [hunk 2]
```diff
@@ -23,7 +23,7 @@
  * covers `comp_`-prefixed tables whose registry row was already removed, and the registry
  * covers registered components whose table has not been materialized yet.
  *
- * @module domains/components/services/teardown-entity-component-data
+ * @module domains/field-groups/services/teardown-entity-component-data
```
[the remark this answers is not in the document]
Comment (mobeenabdullah) [reply packages/nextly/src/domains/field-groups/services/teardown-entity-field-group-data.ts]: Confirmed and fixed in `98ab25ba`.

This is a category I should have swept when I moved the directories, so I did that rather than fixing the one you cited: **nine stale `@module` tags**, not one. Also `domains/field-groups/index.ts` (`domains/components`), `register-field-group-schemas.ts`, `schemas/dynamic-field-groups/index.ts` (your sibling finding), and all five under `field-groups/config/`.

Left alone deliberately: `domains/versions/tag-component-types.ts`, `domains/webhooks/expand-component-fields.ts` and `plugins/codegen/component-import-map.ts`. Those files did not move and are named for the `component` **field type**, so their tags are correct.

File: packages/nextly/src/schemas/dynamic-field-groups/index.ts [hunk 3]
```diff
@@ -14,7 +14,7 @@
  *   type DynamicFieldGroupInsert,
  *   type FieldGroupSource,
  *   type FieldGroupMigrationStatus,
- * } from '@nextly/schemas/dynamic-components';
+ * } from '@nextly/schemas/dynamic-field-groups';
```
[the remark this answers is not in the document]
Comment (mobeenabdullah) [reply packages/nextly/src/schemas/dynamic-field-groups/index.ts:17]: Confirmed and fixed in `98ab25ba` as part of the `@module` sweep described on the sibling thread. `schemas/dynamic-field-groups/index.ts` now documents `schemas/dynamic-field-groups`.

Your qualifier was the important part and I followed it exactly: **stored-table references are unchanged**. The Drizzle *symbols* moved (`dynamicComponents*` → `dynamicFieldGroups*`) but the table name string still comes from `STORAGE_FORMAT.registryTable`, which flips in B2 alongside the migration. Renaming the doc without renaming the table is the intended end state for this slice.

File: packages/nextly/src/domains/field-groups/__tests__/field-group-data-service.test.ts [hunk 4]
```diff
@@ -33,17 +33,17 @@ function createCtx(
...
 
-  const service = new ComponentDataService(
-    adapter as unknown as Parameters<typeof ComponentDataService>[0],
+  const service = new FieldGroupDataService(
+    adapter as unknown as Parameters<typeof FieldGroupDataService>[0],
     logger,
-    registry as unknown as Parameters<typeof ComponentDataService>[2],
-    relationship as unknown as Parameters<typeof ComponentDataService>[3]
+    registry as unknown as Parameters<typeof FieldGroupDataService>[2],
+    relationship as unknown as Parameters<typeof FieldGroupDataService>[3]
```
[the remark this answers is not in the document]
Comment (mobeenabdullah) [reply packages/nextly/src/domains/field-groups/__tests__/field-group-data-service.test.ts]: Confirmed and fixed in `98ab25ba` — `ConstructorParameters<typeof FieldGroupDataService>` at all four sites, plus one more you did not cite: `field-group-registry-service.test.ts:25` had the same pattern.

You are right that `Parameters<T>` is the wrong utility for a constructor. Worth being precise about the impact, though, rather than overstating the fix: because the surrounding expression is `as unknown as …`, **neither form was enforced by the compiler**. I checked by changing an index from `[0]` to `[1]` and re-running `check-types`: still zero errors, because `as unknown as X` compiles for any `X`. So this is a correctness-of-intent fix that makes the tuple index mean what it says, not a behavioural one, and I could not give you a break-proof test for it. Flagging that rather than claiming a proof I do not have.

The pattern is pre-existing; this PR only renamed the class it points at.

File: packages/nextly/src/api/field-groups-detail.ts [hunk 5]
```diff
@@ -39,9 +39,9 @@ interface RouteContext {
   params: Promise<{ slug: string }>;
 }
 
-async function getComponentRegistry(): Promise<ComponentRegistryService> {
+async function getComponentRegistry(): Promise<FieldGroupRegistryService> {
   await getCachedNextly();
-  return getService("componentRegistryService");
+  return getService("fieldGroupRegistryService");
```
[the remark this answers is not in the document]
Comment (mobeenabdullah) [reply packages/nextly/src/api/field-groups-detail.ts:44]: Partly taken, partly pushed back on.

**Taken:** the genuinely non-obvious thing here is that field-group-named modules still expose **component-named methods and types** — `getComponentRegistryFromDI()` returning a `FieldGroupRegistryService`, `getAllComponents()`, `SaveComponentDataParams`. That mismatch reads like an oversight and is not, so I documented the seam in `98ab25ba` at three places: `dispatcher/helpers/di.ts` (why the helper keeps its name while the container key moved), `services/field-groups/field-group-data-service.ts` (why the re-exported parameter types keep component wording), and `register-field-group-schemas.ts` (why registry rows and runtime tables keep `comp_`).

**Pushed back on:** annotating every changed line. The bulk of this diff is import specifiers whose module moved; a comment on each would restate the line above it and add noise to a 99-file mechanical rename. The rule exists so a reader can tell *why* a change was made, and for a pure path rewrite the rename itself is the why. I applied it where the result is surprising, which is the seam above.

File: packages/nextly/src/services/collections/collection-entry-service.ts [hunk 6]
```diff
@@ -50,7 +50,7 @@ import type { PaginatedResponse } from "../../types/pagination";
 import type { AccessControlService } from "../access";
 import { BaseService } from "../base-service";
 import type { CollectionFileManager } from "../collection-file-manager";
-import type { ComponentDataService } from "../components/component-data-service";
+import type { FieldGroupDataService } from "../field-groups/field-group-data-service";
```
[the remark this answers is not in the document]
Comment (mobeenabdullah) [reply packages/nextly/src/services/collections/collection-entry-service.ts:53]: Same disposition as the sibling thread, and the substantive half is done in `98ab25ba`: `services/field-groups/field-group-data-service.ts` now explains that it is a re-export barrel and that its parameter types keep component wording because they describe the stored `component` field type and its `comp_` tables, which are data contracts rather than internal naming.

For `collection-entry-service.ts` I did not add per-line comments. Lines 53, 92 and 140-151 are an import specifier, an optional dependency and forwarding that dependency to two sub-services; none changed behaviour and none is surprising once the import path is read. Adding three comments restating them would make the file harder to scan, not easier.

**Comment by mobeenabdullah** [comment]
@codex please review this PR

**Comment by mobeenabdullah** [comment]
@coderabbitai review

**Comment by mobeenabdullah** [comment]
@greptileai review

File: packages/nextly/src/config.ts [hunk 7]
```diff
@@ -88,7 +88,7 @@ export {
   type FieldGroupConfig,
   type FieldGroupLabel,
   type FieldGroupAdminOptions,
-} from "./components/config";
+} from "./field-groups/config";
```
[the remark this answers is not in the document]
Comment (mobeenabdullah) [reply packages/nextly/src/config.ts:91]: Confirmed and fixed in `5b06237a`. `docs/configuration/field-groups.mdx:10` is the guide's own "Source of truth" callout, so pointing it at deleted paths was the worst possible place to leave stale. Both now read `packages/nextly/src/field-groups/config/`.

Swept the category rather than the two cited paths: no doc anywhere still references `src/components/config`, `src/domains/components/`, `src/services/components/` or `src/schemas/dynamic-components`. The remaining `src/components/` hits in `docs/admin/branding.mdx`, `docs/admin/builder.mdx`, `docs/getting-started/project-structure.mdx` and `docs/templates/blog.mdx` are React component directories in the admin package and the Blog template, which did not move.

File: packages/admin/src/lib/plugins/plugin-components.ts [hunk 8]
```diff
@@ -19,7 +19,7 @@
  * ```typescript
  * // packages/plugin-foo/src/admin/register.ts
  * import { registerComponents } from '@nextlyhq/admin/lib/component-registry';
- * import { FooView, FooButton } from './components';
+ * import { FooView, FooButton } from './field-groups';
```
[the remark this answers is not in the document]
Comment (mobeenabdullah) [reply packages/admin/src/lib/plugins/plugin-components.ts]: You are right, and this was **my bug, not a judgement call** — thank you for catching it. Reverted in `5b06237a`; both examples read `from './components'` again.

Cause: my rename sweep confined path rewrites to lines matching `from "…"`, which was meant to protect string literals — but a **JSDoc example line** also matches that shape. So it rewrote two illustrative imports in documentation for registering **React admin components**, exactly the meaning of "components" that must never be renamed in this program.

Because a mis-scoped regex is a category rather than a one-off, I diffed the whole branch for other `./field-groups` specifiers introduced in admin and plugin packages. These two were the only ones; the remaining hits were stale build output under `packages/admin/dist/`.

File: packages/nextly/src/di/register.ts [hunk 9]
```diff
@@ -303,9 +303,9 @@ export interface ServiceMap {
   mediaService: UnifiedMediaService;
   singleRegistryService: SingleRegistryService;
   singleEntryService: SingleEntryService;
-  componentRegistryService: ComponentRegistryService;
-  componentSchemaService: ComponentSchemaService;
-  componentDataService: ComponentDataService;
+  fieldGroupRegistryService: FieldGroupRegistryService;
+  fieldGroupSchemaService: FieldGroupSchemaService;
+  fieldGroupDataService: FieldGroupDataService;
```
[the remark this answers is not in the document]
Comment (mobeenabdullah) [reply packages/nextly/src/di/register.ts:308]: Verified, and you are right on the facts: **my PR description was wrong.** `getService` and `ServiceMap` are exported from `src/index.ts:279-284` and appear 8 times in the built `dist/index.d.ts`, so these container keys are a public surface, not an internal detail. I have corrected the claim rather than leaving it standing.

**I am not adding compatibility aliases, and that is a deliberate policy call rather than a disagreement with your analysis.** The founder's standing directive for this program is explicit: *"no need to keep alias. we'll do full migration. no dead/redundant code please. there are no public users. its just us and our client sites."* Every prior slice followed it — A1 renamed the config key with no alias, A3a moved the REST routes with none, A4 dropped `/admin/builder/components` with none. Aliasing here would make this the one inconsistent slice, and would leave dead keys the directive exists to prevent.

What I have done instead is stop under-describing it. The changeset now names all three renamed keys, states plainly that the old ones are not aliased and no longer resolve, and no longer claims API surfaces are unchanged.

File: .changeset/field-groups-internal.md [hunk 10]
```diff
@@ -0,0 +1,25 @@
...
+"@nextlyhq/plugin-page-builder": patch
+"@nextlyhq/plugin-seo": patch
+"@nextlyhq/plugin-sdk": patch
+"@nextlyhq/eslint-config": patch
+"@nextlyhq/prettier-config": patch
+"@nextlyhq/telemetry": patch
+"@nextlyhq/tsconfig": patch
+---
+
+Internal modules, services and DI keys for reusable field structures now use field-group naming. Removes an unused schema-code generator from the field group schema service. No stored data, table names, config keys or API surfaces change.
```
[the remark this answers is not in the document]
Comment (mobeenabdullah) [reply .changeset/field-groups-internal.md]: Correct, and it follows from the sibling finding: since `getService("componentSchemaService")` is publicly exported, `generateSchemaCode()` was reachable through it even though nothing in this repo called it. "No API surface changes" was an inaccurate claim on my part.

Fixed in `5b06237a` by treating it as what it is: the changeset now states that the field group schema service drops `generateSchemaCode()` and that it was reachable through that accessor.

Keeping a compatibility implementation would mean retaining 346 lines of a code generator with no caller, which is the specific thing the no-dead-code directive rules out. The removal stays, described honestly, and the founder can weigh it with the accurate description in front of them rather than the one I originally wrote.

Worth noting for scope: the class itself is **not** removed. `FieldGroupSchemaService.generateRuntimeSchema()` is live and used at `init/reload-config.ts`; only the unused code-emitting path and its five exclusively-private helpers are gone.

**Comment by mobeenabdullah** [comment]
@codex please review this PR

**Comment by mobeenabdullah** [comment]
@coderabbitai review

**Comment by mobeenabdullah** [comment]
@greptileai review

**Comment by mobeenabdullah** [comment]
**Correction to the PR description, raised by Codex and confirmed.**

The description said no API surfaces change. That is wrong: `getService` and `ServiceMap` are exported from `src/index.ts:279-284` and appear in the built `dist/index.d.ts`, so the three renamed container keys (`componentRegistryService`, `componentSchemaService`, `componentDataService`) are a public surface, and `generateSchemaCode()` was reachable through `getService("componentSchemaService")`.

No aliases have been added, per the standing no-alias directive that A1, A3a and A4 all followed. Instead the changeset now names the three renamed keys, says the old ones no longer resolve, and records the `generateSchemaCode()` removal. Flagging it here so the accurate description is what gets reviewed, not the original one.

**Comment by mobeenabdullah** [comment]
@codex please review this PR

**Comment by mobeenabdullah** [comment]
@coderabbitai review

**Comment by mobeenabdullah** [comment]
@greptileai review

**Comment by mobeenabdullah** [comment]
**Rebased onto `962fd25c` to resolve a semantic conflict with main.**

CI failed on the previous head with a genuine type error, not a flake:

```
src/api/versions-access.ts(438,40): error TS2345:
  Argument of type '"componentRegistryService"' is not assignable to parameter of type 'keyof ServiceMap'
```

Cause: #391 (versions diff engine) merged while this PR was in review and added a new `getService("componentRegistryService")` call. `git merge-tree` reports **zero textual conflicts** because the two changes touch different files, but the merged tree does not compile: main added a caller for the exact container key this PR renames. Worth noting for the remaining slices that a clean merge check is not evidence a branch still builds against main.

Fixed by rebasing and renaming that call site to `fieldGroupRegistryService`. Also ran `pnpm install`, since #391 introduced `@sanity/diff-match-patch`.

Re-verified after the rebase rather than assuming it was harmless: `check-types` 19/19, lint clean, build clean, and all four stored-contract guards still intact (manifest `ManifestKind`, the pre-rename namespace accessor, the export-contract legacy-names list, and the plugin JSDoc example for React admin components).

The only two branch-only test failures were bcrypt **timing** assertions in `src/auth/password/password.test.ts` — a file this PR does not touch (empty diff against main) which passes 42/42 in isolation.

File: packages/nextly/src/field-groups/config/validate-field-group.ts [hunk 11]
```diff
@@ -303,11 +303,10 @@ function validateFields(
...
 
-  // Why: empty fields list is now valid for both code-first defines and
-  // the new modal-driven create flow (Builder redesign PR 2/3). System
-  // columns are auto-injected at runtime so a "fieldless" Component
-  // still has id, title, slug. Devs can scaffold first and add fields
-  // incrementally.
+  // An empty fields list is valid for both code-first defines and the
+  // modal-driven create flow. System columns are auto-injected at runtime, so a
+  // fieldless field group still has id, title and slug, which lets an author
+  // scaffold first and add fields incrementally.
```
[the remark this answers is not in the document]
Comment (mobeenabdullah) [reply packages/nextly/src/field-groups/config/validate-field-group.ts]: Confirmed, and this one is squarely on me. Fixed in `16c28698`.

I wrote that sentence **in this PR** while rewriting the comment that had referenced "Builder redesign PR 2/3", and I carried the old claim across without checking it. `title` and `slug` are collection columns; a field group's table gets its id plus the parent-binding system columns `_parent_id`, `_parent_table`, `_parent_field` and `_order` (`schemas/storage-format.ts:43-46`), and `_component_type` for a dynamic zone.

Reworded to describe them by role instead of naming a fixed list, since the exact set is owned by `STORAGE_FORMAT` and would drift again:

> A field group's table still gets its id and the system columns that bind a row to its parent entry, so a fieldless group is a usable table and an author can scaffold first and add fields later.

Worth naming the failure mode: rewriting a comment to remove a process reference is still a content change, and I treated it as cosmetic. It was not.

File: packages/nextly/src/services/field-groups/field-group-schema-service.ts [hunk 12]
```diff
@@ -0,0 +1,4 @@
+export {
+  FieldGroupSchemaService,
+  type SupportedDialect,
+} from "../../domains/field-groups/services/field-group-schema-service";
```
[the remark this answers is not in the document]
Comment (mobeenabdullah) [reply packages/nextly/src/services/field-groups/field-group-schema-service.ts:7]: Confirmed and fixed in `16c28698`. You are right that a new product-code file consisting only of a re-export explains nothing, and it was inconsistent besides: I had commented the sibling `field-group-data-service.ts` barrel in an earlier round and simply missed this one.

Rather than fix the file you cited, I checked every barrel in the directory and found **two more** with no explanation, `field-group-registry-service.ts` and `index.ts`. All three now carry one:

- the schema-service and index barrels explain that callers outside the domain reach the services through `services/` so the domain layout stays free to move behind them;
- the registry barrel additionally explains why its exported **type** names keep component wording — `ComponentReference`, `UpdateComponentOptions` and the rest describe the stored `component` field type and its references, which are data contracts rather than internal naming, and they move in B2 with the storage flip.

**Comment by mobeenabdullah** [comment]
@codex please review this PR

**Comment by mobeenabdullah** [comment]
@coderabbitai review

**Comment by mobeenabdullah** [comment]
@greptileai review
