### PR TITLE
refactor(root): give the verdict gate's requests an injectable runner

### PR DESCRIPTION
**Pull request by mobeenabdullah**
Step 2 of 2. The first step made the target resolution testable; this one does the same for the requests themselves, which is where the program is wrong about the **world** rather than about a value.

## What this makes reachable

`headOf`, the `gh` wrapper, the fork remote and the stranded count were only exercisable by running the whole command — a process per case, and several of these failures need a *specific* one. The process runner is now a parameter: the command supplies `execFileSync`, a test supplies whatever failure it is describing.

**Fourteen cases, covering both directions of the distinction that matters.** A command that *fails* announces itself. A command that *succeeds having answered nothing* is the dangerous one: its empty result reaches a decision function as evidence, where "nobody reviewed this" and "the reviews could not be read" are the same empty array.

## The sharpest case, and it had no coverage

`ls-remote` **exits 0 for a ref that does not exist.** The success status says only that the question was asked. Taking the first field of an empty line yields `undefined`, and comparing that against the head reports a **moved head** rather than a missing ref — a different verdict, from the same silence.

```
BREAK: remove the empty-answer guard
  × throws when the ref does not exist
```

Also break-verified: `--unshallow` passed unconditionally (it errors on a complete repository, turning a correct count into a failure to answer).

## The regression the CLI suite caught

Adding a sibling module broke invocation through a symlink, and **the suite added in #837 is what found it** — this is the first time that net has caught something.

A bare `./ci-verdict-evidence.mjs` is resolved against the specifier the runtime holds for the main module. Under `--preserve-symlinks-main` that is the **symlink**, so the module is looked for beside the link:

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '…/lnk/ci-verdict-evidence.mjs'
                              imported from '…/lnk/cv.mjs'
```

The sibling is now resolved through this file's real path. That is the import-time half of the same flag the entry guard already accepts two forms for, and reverting it fails the symlink case.

## One implementation, not two

`countStranded` moved rather than being copied — `is-shallow-repository` now appears **zero** times in `ci-verdict.mjs`. Exporting it while leaving the inline block would have been two answers to one question, which is the thing this repository has a rule about.

## Verification

- 91 tests across three suites (14 new).
- Three break-verifications above, each failing for its intended reason.
- Comment gate clean; no changeset (`scripts/` is in no workspace package).

## Note on the pre-push hook

It failed first with 361 `@nextlyhq/ui` `no-unresolved` errors in `packages/admin` — the documented unbuilt-`dist` case in a fresh worktree, not this change, which touches only `scripts/`. `pnpm build` then a clean push, rather than `--no-verify`.

### CODE REVIEW

**Comment by mobeenabdullah** [comment]
@codex please review this PR
